title: David Giongco
url: https://davidgiongco.com
baseurl: ""
markdown: kramdown
theme: minima
permalink: /:title.html
plugins:
  - jekyll-feed
header_pages:
  - values.md
  - blog.md
  - contact.md
